### ISSUE TITLE
Bug:Unused "Lables" parameter in "utilis/stackImages"

### ISSUE THREAD

**Issue by Ujjawal-Rajput** [VisNcoder/OMR-#1]
No argument passed for "Lables" while calling stackImages() in main.py. 
![Screenshot_20240526_233653](https://github.com/VisNcoder/OMR-/assets/77383883/a2a9c0e7-a23b-4360-bd0a-ecaa43e69d09)

A default parameter is used instead, which is Lables=[] in utilis/stackImages.
![Screenshot_20240526_233851](https://github.com/VisNcoder/OMR-/assets/77383883/a5683e52-dd2d-45ec-9dbc-5626b59e1d42)

And the Lables variable never updated in the entire stackImages(). That means the condition "if len(lables) != 0" will always comes out to be False.

So ultimately we can say that this just increasing the lines of code.
If your project works fine already you can remove that for easy understanding.

Thanks for reading !!

**Comment by VisNcoder** [comment]
Thanks  for opening the issue ,  I had updated the labels
